# Generated by Django 4.1.2 on 2022-10-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_artiste_first_name_alter_artiste_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='Song_id',
            new_name='song_id',
        ),
    ]
